version: "3.8"

## DEFINE SERVICES
services:
  ## FRONTEND
  web:
    container_name: WEB
    image: sugarmill/sugar-mill:dev
    build: 
      context: ./sugar-mill/client
      target: Development
    ports:
      - 8080:8080
    expose: 
      - "8080"  
    volumes:
      - ./sugar-mill/client:/app  

   ## DATABASE
  database:
    container_name: DB
    image: sugarmill/sugar-mill-db:dev
    build:
      context: ./sugar-mill-DB        
    environment:
      SA_PASSWORD: "MyDatabasePassword123"
      ACCEPT_EULA: "Y"
    expose: 
      - "1433"
    ports:
      - 1433:1433
    volumes: 
      - SQL_Data:/var/opt/mssql/data

  ## BACKEND API
  api:
    container_name: API
    depends_on:
      - database
    build: ./sugar-mill/server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=database
      - DB_USER=$MSSQL_USER
      - DB_PASSWORD=$MSSQL_ROOT_PASSWORD
      - DB_NAME=$MSSQL_DATABASE
      - DB_PORT=$MSSQL_DOCKER_PORT
    stdin_open: true
    tty: true

## DEFINE VOLUMES
volumes: 
  SQL_Data:
    external: 
      name: SB_SQL_DATA
